const asd = [
  {
    name: "Estonia",
    topLevelDomain: [".ee"],
    alpha2Code: "EE",
    alpha3Code: "EST",
    callingCodes: ["372"],
    capital: "Tallinn",
    altSpellings: ["EE", "Eesti", "Republic of Estonia", "Eesti Vabariik"],
    subregion: "Northern Europe",
    region: "Europe",
    population: 1331057,
    latlng: [59.0, 26.0],
    demonym: "Estonian",
    area: 45227.0,
    gini: 30.3,
    timezones: ["UTC+02:00"],
    borders: ["LVA", "RUS"],
    nativeName: "Eesti",
    numericCode: "233",
    flags: {
      svg: "https://flagcdn.com/ee.svg",
      png: "https://flagcdn.com/w320/ee.png",
    },
    currencies: [{ code: "EUR", name: "Euro", symbol: "â‚¬" }],
    languages: [
      {
        iso639_1: "et",
        iso639_2: "est",
        name: "Estonian",
        nativeName: "eesti",
      },
    ],
    translations: {
      br: "Estonia",
      pt: "EstÃ³nia",
      nl: "Estland",
      hr: "Estonija",
      fa: "Ø§Ø³ØªÙˆÙ†ÛŒ",
      de: "Estland",
      es: "Estonia",
      fr: "Estonie",
      ja: "ã‚¨ã‚¹ãƒˆãƒ‹ã‚¢",
      it: "Estonia",
      hu: "Ã‰sztorszÃ¡g",
    },
    flag: "https://flagcdn.com/ee.svg",
    regionalBlocs: [{ acronym: "EU", name: "European Union" }],
    cioc: "EST",
    independent: true,
  },
];
